# Welcome to Jekyll!

# Site settings
title: Welcome to The Sentinel Project
email: support@folkvarlabs.com
description: >-
  The Sentinel Project is an advanced security system designed to protect critical infrastructure industries from cyber threats. Using cutting-edge technology and customized algorithms, Sentinel Project aims to reduce the need for human intervention in security incidents, while providing real-time threat intelligence & incident response capabilities.

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: 
github_username: cywf

# Build settings
theme: jekyll-theme-hacker
plugins:
  - jekyll-feed

navigation:
  - title: "Home"
    url: "/"
  - title: "About"
    url: "/about"
  - title: "Sentries"
    url: "/sentries"
  - title: "News"
    url: "/news"
